# Site settings
title: "Professional portfolio"
email: "nico250999@gmail.com"
description: "Portafolio profesional de ciencia de datos, bioinform치tica e investigaci칩n."
baseurl: "" 
url: "https://nicoln-25.github.io"
github_username: "NicoLN-25"
minimal_mistakes_skin: "contrast"
search: true
atom_feed:
  hide: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Nicol치s Luna Ni침o"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "My awesome biography constrained to a sentence or two goes here."
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/nicoln-25"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/nicolas-luna-nino/"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/nicoln-25"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/nicolas-luna-nino/"
    - label: "ResearchGate"
      icon: "fab fa-researchgate"
      url: "https://www.researchgate.net/profile/Nicolas-Luna-Nino-2/research"
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=-nDhqZ4AAAAJ&hl=es"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# pages
header_pages:
  - _pages/about.md
  - _pages/research-cv.md
